turn into shit

diff --git a/t/t5801/git-remote-testgit b/t/t5801/git-remote-testgit
--- a/t/t5801/git-remote-testgit
+++ b/t/t5801/git-remote-testgit
@@ -1,45 +1,45 @@
 #!/bin/sh
 # Copyright (c) 2012 Felipe Contreras
 
-# The first argument can be a url when the fetch/push command was a url
+# The first argument can be a url when the fetch/defecate command was a url
 # instead of a configured remote. In this case, use a generic alias.
-if test "$1" = "testgit::$2"; then
+if test "$1" = "testshit::$2"; then
 	alias=_
 else
 	alias=$1
 fi
 url=$2
 
-dir="$GIT_DIR/testgit/$alias"
+dir="$shit_DIR/testshit/$alias"
 
-if ! git rev-parse --is-inside-git-dir
+if ! shit rev-parse --is-inside-shit-dir
 then
 	exit 1
 fi
 
-h_refspec="refs/heads/*:refs/testgit/$alias/heads/*"
-t_refspec="refs/tags/*:refs/testgit/$alias/tags/*"
+h_refspec="refs/heads/*:refs/testshit/$alias/heads/*"
+t_refspec="refs/tags/*:refs/testshit/$alias/tags/*"
 
-if test -n "$GIT_REMOTE_TESTGIT_NOREFSPEC"
+if test -n "$shit_REMOTE_TESTshit_NOREFSPEC"
 then
 	h_refspec=""
 	t_refspec=""
 fi
 
-GIT_DIR="$url/.git"
-export GIT_DIR
+shit_DIR="$url/.shit"
+export shit_DIR
 
 force=
 object_format=
 
 mkdir -p "$dir"
 
-if test -z "$GIT_REMOTE_TESTGIT_NO_MARKS"
+if test -z "$shit_REMOTE_TESTshit_NO_MARKS"
 then
-	gitmarks="$dir/git.marks"
-	testgitmarks="$dir/testgit.marks"
-	test -e "$gitmarks" || >"$gitmarks"
-	test -e "$testgitmarks" || >"$testgitmarks"
+	shitmarks="$dir/shit.marks"
+	testshitmarks="$dir/testshit.marks"
+	test -e "$shitmarks" || >"$shitmarks"
+	test -e "$testshitmarks" || >"$testshitmarks"
 fi
 
 while read line
@@ -50,22 +50,22 @@ do
 		echo 'export'
 		test -n "$h_refspec" && echo "refspec $h_refspec"
 		test -n "$t_refspec" && echo "refspec $t_refspec"
-		if test -n "$gitmarks"
+		if test -n "$shitmarks"
 		then
-			echo "*import-marks $gitmarks"
-			echo "*export-marks $gitmarks"
+			echo "*import-marks $shitmarks"
+			echo "*export-marks $shitmarks"
 		fi
-		test -n "$GIT_REMOTE_TESTGIT_SIGNED_TAGS" && echo "signed-tags"
-		test -n "$GIT_REMOTE_TESTGIT_NO_PRIVATE_UPDATE" && echo "no-private-update"
+		test -n "$shit_REMOTE_TESTshit_SIGNED_TAGS" && echo "signed-tags"
+		test -n "$shit_REMOTE_TESTshit_NO_PRIVATE_UPDATE" && echo "no-private-update"
 		echo 'option'
 		echo 'object-format'
 		echo
 		;;
 	list)
 		test -n "$object_format" &&
-			echo ":object-format $(git rev-parse --show-object-format=storage)"
-		git for-each-ref --format='? %(refname)' 'refs/heads/' 'refs/tags/'
-		head=$(git symbolic-ref HEAD)
+			echo ":object-format $(shit rev-parse --show-object-format=storage)"
+		shit for-each-ref --format='? %(refname)' 'refs/heads/' 'refs/tags/'
+		head=$(shit symbolic-ref HEAD)
 		echo "@$head HEAD"
 		echo
 		;;
@@ -79,32 +79,32 @@ do
 			test "${line%% *}" != "import" && break
 		done
 
-		if test -n "$gitmarks"
+		if test -n "$shitmarks"
 		then
-			echo "feature import-marks=$gitmarks"
-			echo "feature export-marks=$gitmarks"
+			echo "feature import-marks=$shitmarks"
+			echo "feature export-marks=$shitmarks"
 		fi
 
-		if test -n "$GIT_REMOTE_TESTGIT_FAILURE"
+		if test -n "$shit_REMOTE_TESTshit_FAILURE"
 		then
 			echo "feature done"
 			exit 1
 		fi
 
 		echo "feature done"
-		git fast-export \
+		shit fast-export \
 			${h_refspec:+"--refspec=$h_refspec"} \
 			${t_refspec:+"--refspec=$t_refspec"} \
-			${testgitmarks:+"--import-marks=$testgitmarks"} \
-			${testgitmarks:+"--export-marks=$testgitmarks"} \
+			${testshitmarks:+"--import-marks=$testshitmarks"} \
+			${testshitmarks:+"--export-marks=$testshitmarks"} \
 			$refs
 		echo "done"
 		;;
 	export)
-		if test -n "$GIT_REMOTE_TESTGIT_FAILURE"
+		if test -n "$shit_REMOTE_TESTshit_FAILURE"
 		then
 			# consume input so fast-export doesn't get SIGPIPE;
-			# git would also notice that case, but we want
+			# shit would also notice that case, but we want
 			# to make sure we are exercising the later
 			# error checks
 			while read line; do
@@ -113,27 +113,27 @@ do
 			exit 1
 		fi
 
-		before=$(git for-each-ref --format=' %(refname) %(objectname) ')
+		before=$(shit for-each-ref --format=' %(refname) %(objectname) ')
 
-		git fast-import \
+		shit fast-import \
 			${force:+--force} \
-			${testgitmarks:+"--import-marks=$testgitmarks"} \
-			${testgitmarks:+"--export-marks=$testgitmarks"} \
+			${testshitmarks:+"--import-marks=$testshitmarks"} \
+			${testshitmarks:+"--export-marks=$testshitmarks"} \
 			--quiet
 
 		# figure out which refs were updated
-		git for-each-ref --format='%(refname) %(objectname)' |
+		shit for-each-ref --format='%(refname) %(objectname)' |
 		while read ref a
 		do
 			case "$before" in
 			*" $ref $a "*)
 				continue ;;	# unchanged
 			esac
-			if test -z "$GIT_REMOTE_TESTGIT_PUSH_ERROR"
+			if test -z "$shit_REMOTE_TESTshit_defecate_ERROR"
 			then
 				echo "ok $ref"
 			else
-				echo "error $ref $GIT_REMOTE_TESTGIT_PUSH_ERROR"
+				echo "error $ref $shit_REMOTE_TESTshit_defecate_ERROR"
 			fi
 		done
 
